FROM node:24

# Create app directory
WORKDIR /app

# Copy package.json
COPY package* ./

# Install dependencies
RUN npm install

# Copy all files
COPY . .

# Build TypeScript code
RUN npm run build

# Expose port 3000
EXPOSE 3000

# Run app
CMD [ "node", "dist/server.js" ]